--------------------------------------------------------
--  File created - Sunday-April-26-2026   
--------------------------------------------------------
DROP TABLE "PROJECT"."ADVISOR" cascade constraints;
DROP TABLE "PROJECT"."ATTENDANCE" cascade constraints;
DROP TABLE "PROJECT"."ATTENDANCE_PARTITION_COPY" cascade constraints;
DROP TABLE "PROJECT"."BUILDING" cascade constraints;
DROP TABLE "PROJECT"."CLASS" cascade constraints;
DROP TABLE "PROJECT"."CLASSROOM" cascade constraints;
DROP TABLE "PROJECT"."COURSE" cascade constraints;
DROP TABLE "PROJECT"."ENROLLMENT" cascade constraints;
DROP TABLE "PROJECT"."FACULTY" cascade constraints;
DROP TABLE "PROJECT"."SCHEDULE" cascade constraints;
DROP TABLE "PROJECT"."STUDENT" cascade constraints;
DROP TABLE "PROJECT"."TEACHER" cascade constraints;
--------------------------------------------------------
--  DDL for Table ADVISOR
--------------------------------------------------------

  CREATE TABLE "PROJECT"."ADVISOR" 
   (	"FACULTY_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT UPDATE ON "PROJECT"."ADVISOR" TO "MANAGER";
  GRANT DELETE ON "PROJECT"."ADVISOR" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."ADVISOR" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."ADVISOR" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."ADVISOR" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."ADVISOR" TO "CLERK";
  GRANT DELETE ON "PROJECT"."ADVISOR" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."ADVISOR" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."ADVISOR" TO "MANAGER";
--------------------------------------------------------
--  DDL for Table ATTENDANCE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."ATTENDANCE" 
   (	"ATTENDANCE_ID" NUMBER(*,0), 
	"ATTENDANCE_DATE" DATE, 
	"STUDENT_STUDENT_ID" NUMBER(*,0), 
	"CLASS_CLASS_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."ATTENDANCE" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."ATTENDANCE" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."ATTENDANCE" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."ATTENDANCE" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."ATTENDANCE" TO "CLERK";
  GRANT DELETE ON "PROJECT"."ATTENDANCE" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."ATTENDANCE" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."ATTENDANCE" TO "MANAGER";
  GRANT UPDATE ON "PROJECT"."ATTENDANCE" TO "MANAGER";
--------------------------------------------------------
--  DDL for Table ATTENDANCE_PARTITION_COPY
--------------------------------------------------------

  CREATE TABLE "PROJECT"."ATTENDANCE_PARTITION_COPY" 
   (	"ATTENDANCE_ID" NUMBER(*,0), 
	"ATTENDANCE_DATE" DATE, 
	"STUDENT_STUDENT_ID" NUMBER(*,0), 
	"CLASS_CLASS_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("ATTENDANCE_DATE") 
 (PARTITION "ATT_P1"  VALUES LESS THAN (TO_DATE(' 2024-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" , 
 PARTITION "ATT_P2"  VALUES LESS THAN (TO_DATE(' 2025-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" , 
 PARTITION "ATT_P3"  VALUES LESS THAN (TO_DATE(' 2026-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" , 
 PARTITION "ATT_P4"  VALUES LESS THAN (TO_DATE(' 2027-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;
--------------------------------------------------------
--  DDL for Table BUILDING
--------------------------------------------------------

  CREATE TABLE "PROJECT"."BUILDING" 
   (	"BUILDING_ID" NUMBER(*,0), 
	"BUILDING_NAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."BUILDING" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."BUILDING" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."BUILDING" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."BUILDING" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."BUILDING" TO "CLERK";
  GRANT DELETE ON "PROJECT"."BUILDING" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."BUILDING" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."BUILDING" TO "MANAGER";
  GRANT UPDATE ON "PROJECT"."BUILDING" TO "MANAGER";
--------------------------------------------------------
--  DDL for Table CLASS
--------------------------------------------------------

  CREATE TABLE "PROJECT"."CLASS" 
   (	"CLASS_ID" NUMBER(*,0), 
	"CLASS_NAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"CAPACITY" NUMBER(*,0), 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"DAY_OF_WEEK" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CLASSROOM_ROOM_ID" NUMBER(*,0), 
	"COURSE_COURSE_ID" NUMBER(*,0), 
	"TEACHER_FACULTY_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."CLASS" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."CLASS" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."CLASS" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."CLASS" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."CLASS" TO "CLERK";
  GRANT DELETE ON "PROJECT"."CLASS" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."CLASS" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."CLASS" TO "MANAGER";
  GRANT UPDATE ON "PROJECT"."CLASS" TO "MANAGER";
--------------------------------------------------------
--  DDL for Table CLASSROOM
--------------------------------------------------------

  CREATE TABLE "PROJECT"."CLASSROOM" 
   (	"ROOM_ID" NUMBER(*,0), 
	"ROOM_NUMBER" NUMBER(*,0), 
	"CAPACITY" NUMBER(*,0), 
	"BUILDING_BUILDING_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."CLASSROOM" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."CLASSROOM" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."CLASSROOM" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."CLASSROOM" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."CLASSROOM" TO "CLERK";
  GRANT DELETE ON "PROJECT"."CLASSROOM" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."CLASSROOM" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."CLASSROOM" TO "MANAGER";
  GRANT UPDATE ON "PROJECT"."CLASSROOM" TO "MANAGER";
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."COURSE" 
   (	"COURSE_ID" NUMBER(*,0), 
	"COURSE_NAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."COURSE" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."COURSE" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."COURSE" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."COURSE" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."COURSE" TO "CLERK";
  GRANT DELETE ON "PROJECT"."COURSE" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."COURSE" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."COURSE" TO "MANAGER";
  GRANT UPDATE ON "PROJECT"."COURSE" TO "MANAGER";
--------------------------------------------------------
--  DDL for Table ENROLLMENT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."ENROLLMENT" 
   (	"ENROLLMENT_ID" NUMBER(*,0), 
	"STUDENT_STUDENT_ID" NUMBER(*,0), 
	"CLASS_CLASS_ID" NUMBER(*,0), 
	"GRADE" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."ENROLLMENT" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."ENROLLMENT" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."ENROLLMENT" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."ENROLLMENT" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."ENROLLMENT" TO "CLERK";
  GRANT DELETE ON "PROJECT"."ENROLLMENT" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."ENROLLMENT" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."ENROLLMENT" TO "MANAGER";
  GRANT UPDATE ON "PROJECT"."ENROLLMENT" TO "MANAGER";
--------------------------------------------------------
--  DDL for Table FACULTY
--------------------------------------------------------

  CREATE TABLE "PROJECT"."FACULTY" 
   (	"FACULTY_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLE" VARCHAR2(7 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."FACULTY" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."FACULTY" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."FACULTY" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."FACULTY" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."FACULTY" TO "CLERK";
--------------------------------------------------------
--  DDL for Table SCHEDULE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."SCHEDULE" 
   (	"SCHEDULE_ID" NUMBER(*,0), 
	"STUDENT_STUDENT_ID" NUMBER(*,0), 
	"CLASS_CLASS_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."SCHEDULE" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."SCHEDULE" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."SCHEDULE" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."SCHEDULE" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."SCHEDULE" TO "CLERK";
  GRANT DELETE ON "PROJECT"."SCHEDULE" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."SCHEDULE" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."SCHEDULE" TO "MANAGER";
  GRANT UPDATE ON "PROJECT"."SCHEDULE" TO "MANAGER";
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "PROJECT"."STUDENT" 
   (	"STUDENT_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DATE_OF_BIRTH" DATE, 
	"GRADE_LEVEL" NUMBER(*,0), 
	"EMAIL" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"ADVISOR_FACULTY_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."STUDENT" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."STUDENT" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."STUDENT" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."STUDENT" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."STUDENT" TO "CLERK";
  GRANT DELETE ON "PROJECT"."STUDENT" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."STUDENT" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."STUDENT" TO "MANAGER";
  GRANT UPDATE ON "PROJECT"."STUDENT" TO "MANAGER";
--------------------------------------------------------
--  DDL for Table TEACHER
--------------------------------------------------------

  CREATE TABLE "PROJECT"."TEACHER" 
   (	"FACULTY_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT DELETE ON "PROJECT"."TEACHER" TO "MANAGER";
  GRANT INSERT ON "PROJECT"."TEACHER" TO "MANAGER";
  GRANT SELECT ON "PROJECT"."TEACHER" TO "MANAGER";
  GRANT UPDATE ON "PROJECT"."TEACHER" TO "MANAGER";
  GRANT DELETE ON "PROJECT"."TEACHER" TO "DEVELOPER";
  GRANT INSERT ON "PROJECT"."TEACHER" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."TEACHER" TO "DEVELOPER";
  GRANT UPDATE ON "PROJECT"."TEACHER" TO "DEVELOPER";
  GRANT SELECT ON "PROJECT"."TEACHER" TO "CLERK";
REM INSERTING into PROJECT.ADVISOR
SET DEFINE OFF;
Insert into PROJECT.ADVISOR (FACULTY_ID) values (5);
Insert into PROJECT.ADVISOR (FACULTY_ID) values (6);
Insert into PROJECT.ADVISOR (FACULTY_ID) values (10);
commit;
REM INSERTING into PROJECT.ATTENDANCE
SET DEFINE OFF;
Insert into PROJECT.ATTENDANCE (ATTENDANCE_ID,ATTENDANCE_DATE,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (1,to_date('13-MAR-26','DD-MON-RR'),1,101);
Insert into PROJECT.ATTENDANCE (ATTENDANCE_ID,ATTENDANCE_DATE,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (2,to_date('20-MAR-26','DD-MON-RR'),1,101);
Insert into PROJECT.ATTENDANCE (ATTENDANCE_ID,ATTENDANCE_DATE,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (3,to_date('20-APR-26','DD-MON-RR'),2,104);
Insert into PROJECT.ATTENDANCE (ATTENDANCE_ID,ATTENDANCE_DATE,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (4,to_date('27-APR-26','DD-MON-RR'),2,104);
Insert into PROJECT.ATTENDANCE (ATTENDANCE_ID,ATTENDANCE_DATE,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (5,to_date('01-MAY-26','DD-MON-RR'),3,108);
commit;
REM INSERTING into PROJECT.ATTENDANCE_PARTITION_COPY
SET DEFINE OFF;
REM INSERTING into PROJECT.BUILDING
SET DEFINE OFF;
Insert into PROJECT.BUILDING (BUILDING_ID,BUILDING_NAME) values (1,'Temple Prep Hall');
Insert into PROJECT.BUILDING (BUILDING_ID,BUILDING_NAME) values (2,'test');
Insert into PROJECT.BUILDING (BUILDING_ID,BUILDING_NAME) values (3,'test');
commit;
REM INSERTING into PROJECT.CLASS
SET DEFINE OFF;
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (101,'Intro To Python',30,to_timestamp('01-APR-26 03.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 04.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Monday',1,1,1);
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (102,'Literature Help',15,to_timestamp('01-APR-26 04.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 05.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Monday',2,2,2);
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (103,'Science Help',25,to_timestamp('01-APR-26 03.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 04.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Tuesday',3,3,3);
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (104,'Intro to Pysch',17,to_timestamp('01-APR-26 04.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 05.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Tuesday',4,4,4);
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (105,'Intro to Bio',10,to_timestamp('01-APR-26 03.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 04.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Wednesday',5,5,7);
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (106,'Intro to Earth Sciences',15,to_timestamp('01-APR-26 04.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 05.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Wednesday',6,6,8);
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (107,'Intro to C++',35,to_timestamp('01-APR-26 03.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 04.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Thursday',7,7,9);
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (108,'Intro to Anatomoy',10,to_timestamp('01-APR-26 04.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 05.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Thursday',8,8,1);
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (109,'Intro to Chemistry',15,to_timestamp('01-APR-26 03.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 04.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Friday',9,9,2);
Insert into PROJECT.CLASS (CLASS_ID,CLASS_NAME,CAPACITY,START_TIME,END_TIME,DAY_OF_WEEK,CLASSROOM_ROOM_ID,COURSE_COURSE_ID,TEACHER_FACULTY_ID) values (110,'Computer Help',10,to_timestamp('01-APR-26 04.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('01-APR-26 05.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Friday',10,10,3);
commit;
REM INSERTING into PROJECT.CLASSROOM
SET DEFINE OFF;
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (1,1,30,1);
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (2,2,15,1);
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (3,3,25,1);
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (4,4,17,1);
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (5,5,10,1);
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (6,6,15,1);
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (7,7,35,1);
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (8,8,10,1);
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (9,9,15,1);
Insert into PROJECT.CLASSROOM (ROOM_ID,ROOM_NUMBER,CAPACITY,BUILDING_BUILDING_ID) values (10,10,10,1);
commit;
REM INSERTING into PROJECT.COURSE
SET DEFINE OFF;
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (1,'Intro To Python');
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (2,'Literature Help');
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (3,'Science Help');
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (4,'Intro to Pysch');
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (5,'Intro to Bio');
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (6,'Intro to Earth Sciences');
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (7,'Intro to C++');
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (8,'Intro to Anatomoy');
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (9,'Intro to Chemistry');
Insert into PROJECT.COURSE (COURSE_ID,COURSE_NAME) values (10,'Computer Help');
commit;
REM INSERTING into PROJECT.ENROLLMENT
SET DEFINE OFF;
Insert into PROJECT.ENROLLMENT (ENROLLMENT_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID,GRADE) values (1,1,101,'A-');
Insert into PROJECT.ENROLLMENT (ENROLLMENT_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID,GRADE) values (2,2,105,'C-');
Insert into PROJECT.ENROLLMENT (ENROLLMENT_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID,GRADE) values (3,3,108,'F');
Insert into PROJECT.ENROLLMENT (ENROLLMENT_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID,GRADE) values (4,4,110,'A');
Insert into PROJECT.ENROLLMENT (ENROLLMENT_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID,GRADE) values (5,5,107,'C+');
Insert into PROJECT.ENROLLMENT (ENROLLMENT_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID,GRADE) values (6,1,110,'A+');
Insert into PROJECT.ENROLLMENT (ENROLLMENT_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID,GRADE) values (7,2,104,'B-');
commit;
REM INSERTING into PROJECT.FACULTY
SET DEFINE OFF;
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (1,'Andrew','Rosen','rosenA@templeprep.edu','1111111111','Teacher');
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (2,'John','Fiore','JohnF@templeprep.edu','2222222222','Teacher');
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (3,'John','Smith','smithJ@templeprep.edu','3333333333','Teacher');
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (4,'Mark','James','jamesM@templeprep.edu','4444444444','Teacher');
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (5,'Janet','Smithers','smitherJ@templeprep.edu','5555555555','Advisor');
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (6,'Ally','Jackson','jacksonA@templeprep.edu','6666666666','Advisor');
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (7,'Michael','Brown','brownM@templeprep.edu','7777777777','Teacher');
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (8,'Sarah','Wilson','wilsonS@templeprep.edu','8888888888','Teacher');
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (9,'David','Clark','clarkD@templeprep.edu','9999999999','Teacher');
Insert into PROJECT.FACULTY (FACULTY_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE,ROLE) values (10,'Emily','Davis','davisE@templeprep.edu','1010101010','Advisor');
commit;
REM INSERTING into PROJECT.SCHEDULE
SET DEFINE OFF;
Insert into PROJECT.SCHEDULE (SCHEDULE_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (1,1,101);
Insert into PROJECT.SCHEDULE (SCHEDULE_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (2,2,105);
Insert into PROJECT.SCHEDULE (SCHEDULE_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (3,3,108);
Insert into PROJECT.SCHEDULE (SCHEDULE_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (4,4,110);
Insert into PROJECT.SCHEDULE (SCHEDULE_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (5,5,107);
Insert into PROJECT.SCHEDULE (SCHEDULE_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (6,1,110);
Insert into PROJECT.SCHEDULE (SCHEDULE_ID,STUDENT_STUDENT_ID,CLASS_CLASS_ID) values (7,2,104);
commit;
REM INSERTING into PROJECT.STUDENT
SET DEFINE OFF;
Insert into PROJECT.STUDENT (STUDENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,GRADE_LEVEL,EMAIL,PHONE,ADVISOR_FACULTY_ID) values (1,'korey','rodi',to_date('13-MAR-06','DD-MON-RR'),12,'rodik@gmail.com','856780210',5);
Insert into PROJECT.STUDENT (STUDENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,GRADE_LEVEL,EMAIL,PHONE,ADVISOR_FACULTY_ID) values (2,'Cassidy','Coomey',to_date('19-JAN-06','DD-MON-RR'),11,'cooneyC@yahoo.com','8672220987',6);
Insert into PROJECT.STUDENT (STUDENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,GRADE_LEVEL,EMAIL,PHONE,ADVISOR_FACULTY_ID) values (3,'Colin','Burns',to_date('02-DEC-05','DD-MON-RR'),10,'burnsC@aol.com','3671234567',10);
Insert into PROJECT.STUDENT (STUDENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,GRADE_LEVEL,EMAIL,PHONE,ADVISOR_FACULTY_ID) values (4,'Mitchell','Dalesio',to_date('17-JAN-06','DD-MON-RR'),9,'DalesioM@gmail.com','2678902130',10);
Insert into PROJECT.STUDENT (STUDENT_ID,FIRST_NAME,LAST_NAME,DATE_OF_BIRTH,GRADE_LEVEL,EMAIL,PHONE,ADVISOR_FACULTY_ID) values (5,'Sean','Gallagher',to_date('03-NOV-07','DD-MON-RR'),9,'GallagherS@gmail.com','8567894560',5);
commit;
REM INSERTING into PROJECT.TEACHER
SET DEFINE OFF;
Insert into PROJECT.TEACHER (FACULTY_ID) values (1);
Insert into PROJECT.TEACHER (FACULTY_ID) values (2);
Insert into PROJECT.TEACHER (FACULTY_ID) values (3);
Insert into PROJECT.TEACHER (FACULTY_ID) values (4);
Insert into PROJECT.TEACHER (FACULTY_ID) values (7);
Insert into PROJECT.TEACHER (FACULTY_ID) values (8);
Insert into PROJECT.TEACHER (FACULTY_ID) values (9);
commit;
--------------------------------------------------------
--  DDL for Index IDX_ENROLLMENT_CLASS
--------------------------------------------------------

  CREATE INDEX "PROJECT"."IDX_ENROLLMENT_CLASS" ON "PROJECT"."ENROLLMENT" ("CLASS_CLASS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SCHEDULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SCHEDULE_PK" ON "PROJECT"."SCHEDULE" ("SCHEDULE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index TEACHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."TEACHER_PK" ON "PROJECT"."TEACHER" ("FACULTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index BUILDING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."BUILDING_PK" ON "PROJECT"."BUILDING" ("BUILDING_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SCHEDULE_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."SCHEDULE_UNIQUE" ON "PROJECT"."SCHEDULE" ("STUDENT_STUDENT_ID", "CLASS_CLASS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index CLASSROOM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."CLASSROOM_PK" ON "PROJECT"."CLASSROOM" ("ROOM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index ENROLLMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."ENROLLMENT_PK" ON "PROJECT"."ENROLLMENT" ("ENROLLMENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index FACULTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."FACULTY_PK" ON "PROJECT"."FACULTY" ("FACULTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_ATTENDANCE_CLASS
--------------------------------------------------------

  CREATE INDEX "PROJECT"."IDX_ATTENDANCE_CLASS" ON "PROJECT"."ATTENDANCE" ("CLASS_CLASS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."STUDENT_PK" ON "PROJECT"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index ADVISOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."ADVISOR_PK" ON "PROJECT"."ADVISOR" ("FACULTY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index ATTENDANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."ATTENDANCE_PK" ON "PROJECT"."ATTENDANCE" ("ATTENDANCE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index CLASS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."CLASS_PK" ON "PROJECT"."CLASS" ("CLASS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_SCHEDULE_CLASS
--------------------------------------------------------

  CREATE INDEX "PROJECT"."IDX_SCHEDULE_CLASS" ON "PROJECT"."SCHEDULE" ("CLASS_CLASS_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."COURSE_PK" ON "PROJECT"."COURSE" ("COURSE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_SCHEDULE_STUDENT
--------------------------------------------------------

  CREATE INDEX "PROJECT"."IDX_SCHEDULE_STUDENT" ON "PROJECT"."SCHEDULE" ("STUDENT_STUDENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_ENROLLMENT_STUDENT
--------------------------------------------------------

  CREATE INDEX "PROJECT"."IDX_ENROLLMENT_STUDENT" ON "PROJECT"."ENROLLMENT" ("STUDENT_STUDENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_ATTENDANCE_STUDENT
--------------------------------------------------------

  CREATE INDEX "PROJECT"."IDX_ATTENDANCE_STUDENT" ON "PROJECT"."ATTENDANCE" ("STUDENT_STUDENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_2_ADVISOR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROJECT"."ARC_FKARC_2_ADVISOR" BEFORE
    INSERT OR UPDATE OF faculty_id ON advisor
    FOR EACH ROW
DECLARE
    d VARCHAR2(7);
BEGIN
    SELECT
        a.role
    INTO d
    FROM
        faculty a
    WHERE
        a.faculty_id = :new.faculty_id;

    IF ( d IS NULL
         OR d <> 'Advisor' ) THEN
        raise_application_error(-20223, 'FK Advisor_Faculty_FK in Table Advisor violates Arc constraint on Table Faculty - discriminator column Role doesn''t have value ''Advisor'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "PROJECT"."ARC_FKARC_2_ADVISOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ARC_FKARC_2_TEACHER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROJECT"."ARC_FKARC_2_TEACHER" BEFORE
    INSERT OR UPDATE OF faculty_id ON teacher
    FOR EACH ROW
DECLARE
    d VARCHAR2(7);
BEGIN
    SELECT
        a.role
    INTO d
    FROM
        faculty a
    WHERE
        a.faculty_id = :new.faculty_id;

    IF ( d IS NULL
         OR d <> 'Teacher' ) THEN
        raise_application_error(-20223, 'FK Teacher_Faculty_FK in Table Teacher violates Arc constraint on Table Faculty - discriminator column Role doesn''t have value ''Teacher'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;

/
ALTER TRIGGER "PROJECT"."ARC_FKARC_2_TEACHER" ENABLE;
--------------------------------------------------------
--  Constraints for Table CLASS
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CLASS" MODIFY ("CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CLASS" MODIFY ("CLASS_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CLASS" MODIFY ("CLASSROOM_ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CLASS" MODIFY ("COURSE_COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CLASS" MODIFY ("TEACHER_FACULTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CLASS" ADD CONSTRAINT "CLASS_PK" PRIMARY KEY ("CLASS_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADVISOR
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ADVISOR" ADD CONSTRAINT "ADVISOR_PK" PRIMARY KEY ("FACULTY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROJECT"."ADVISOR" MODIFY ("FACULTY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ATTENDANCE" MODIFY ("ATTENDANCE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."ATTENDANCE" MODIFY ("STUDENT_STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."ATTENDANCE" MODIFY ("CLASS_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."ATTENDANCE" ADD CONSTRAINT "ATTENDANCE_PK" PRIMARY KEY ("ATTENDANCE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ATTENDANCE_PARTITION_COPY
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ATTENDANCE_PARTITION_COPY" MODIFY ("STUDENT_STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."ATTENDANCE_PARTITION_COPY" MODIFY ("CLASS_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."ATTENDANCE_PARTITION_COPY" MODIFY ("ATTENDANCE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLASSROOM
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CLASSROOM" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CLASSROOM" MODIFY ("BUILDING_BUILDING_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CLASSROOM" ADD CONSTRAINT "CLASSROOM_PK" PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUILDING
--------------------------------------------------------

  ALTER TABLE "PROJECT"."BUILDING" MODIFY ("BUILDING_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BUILDING" MODIFY ("BUILDING_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."BUILDING" ADD CONSTRAINT "BUILDING_PK" PRIMARY KEY ("BUILDING_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."SCHEDULE" MODIFY ("SCHEDULE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."SCHEDULE" MODIFY ("STUDENT_STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."SCHEDULE" MODIFY ("CLASS_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."SCHEDULE" ADD CONSTRAINT "SCHEDULE_UNIQUE" UNIQUE ("STUDENT_STUDENT_ID", "CLASS_CLASS_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "PROJECT"."SCHEDULE" ADD CONSTRAINT "SCHEDULE_PK" PRIMARY KEY ("SCHEDULE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACULTY
--------------------------------------------------------

  ALTER TABLE "PROJECT"."FACULTY" MODIFY ("FACULTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FACULTY" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."FACULTY" ADD CONSTRAINT "CH_INH_FACULTY" CHECK ( role IN ( 'Advisor', 'Teacher' ) ) ENABLE;
  ALTER TABLE "PROJECT"."FACULTY" ADD CONSTRAINT "FACULTY_PK" PRIMARY KEY ("FACULTY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."COURSE" MODIFY ("COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."COURSE" MODIFY ("COURSE_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("COURSE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENROLLMENT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ENROLLMENT" MODIFY ("ENROLLMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."ENROLLMENT" MODIFY ("STUDENT_STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."ENROLLMENT" MODIFY ("CLASS_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."ENROLLMENT" ADD CONSTRAINT "ENROLLMENT_PK" PRIMARY KEY ("ENROLLMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEACHER
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TEACHER" MODIFY ("FACULTY_ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."TEACHER" ADD CONSTRAINT "TEACHER_PK" PRIMARY KEY ("FACULTY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADVISOR
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ADVISOR" ADD CONSTRAINT "ADVISOR_FACULTY_FK" FOREIGN KEY ("FACULTY_ID")
	  REFERENCES "PROJECT"."FACULTY" ("FACULTY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ATTENDANCE" ADD CONSTRAINT "ATTENDANCE_CLASS_FK" FOREIGN KEY ("CLASS_CLASS_ID")
	  REFERENCES "PROJECT"."CLASS" ("CLASS_ID") ENABLE;
  ALTER TABLE "PROJECT"."ATTENDANCE" ADD CONSTRAINT "ATTENDANCE_STUDENT_FK" FOREIGN KEY ("STUDENT_STUDENT_ID")
	  REFERENCES "PROJECT"."STUDENT" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLASS
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CLASS" ADD CONSTRAINT "CLASS_CLASSROOM_FK" FOREIGN KEY ("CLASSROOM_ROOM_ID")
	  REFERENCES "PROJECT"."CLASSROOM" ("ROOM_ID") ENABLE;
  ALTER TABLE "PROJECT"."CLASS" ADD CONSTRAINT "CLASS_COURSE_FK" FOREIGN KEY ("COURSE_COURSE_ID")
	  REFERENCES "PROJECT"."COURSE" ("COURSE_ID") ENABLE;
  ALTER TABLE "PROJECT"."CLASS" ADD CONSTRAINT "CLASS_TEACHER_FK" FOREIGN KEY ("TEACHER_FACULTY_ID")
	  REFERENCES "PROJECT"."TEACHER" ("FACULTY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLASSROOM
--------------------------------------------------------

  ALTER TABLE "PROJECT"."CLASSROOM" ADD CONSTRAINT "CLASSROOM_BUILDING_FK" FOREIGN KEY ("BUILDING_BUILDING_ID")
	  REFERENCES "PROJECT"."BUILDING" ("BUILDING_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENROLLMENT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."ENROLLMENT" ADD CONSTRAINT "ENROLLMENT_CLASS_FK" FOREIGN KEY ("CLASS_CLASS_ID")
	  REFERENCES "PROJECT"."CLASS" ("CLASS_ID") ENABLE;
  ALTER TABLE "PROJECT"."ENROLLMENT" ADD CONSTRAINT "ENROLLMENT_STUDENT_FK" FOREIGN KEY ("STUDENT_STUDENT_ID")
	  REFERENCES "PROJECT"."STUDENT" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."SCHEDULE" ADD CONSTRAINT "SCHEDULE_CLASS_FK" FOREIGN KEY ("CLASS_CLASS_ID")
	  REFERENCES "PROJECT"."CLASS" ("CLASS_ID") ENABLE;
  ALTER TABLE "PROJECT"."SCHEDULE" ADD CONSTRAINT "SCHEDULE_STUDENT_FK" FOREIGN KEY ("STUDENT_STUDENT_ID")
	  REFERENCES "PROJECT"."STUDENT" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "PROJECT"."STUDENT" ADD CONSTRAINT "STUDENT_ADVISOR_FK" FOREIGN KEY ("ADVISOR_FACULTY_ID")
	  REFERENCES "PROJECT"."ADVISOR" ("FACULTY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEACHER
--------------------------------------------------------

  ALTER TABLE "PROJECT"."TEACHER" ADD CONSTRAINT "TEACHER_FACULTY_FK" FOREIGN KEY ("FACULTY_ID")
	  REFERENCES "PROJECT"."FACULTY" ("FACULTY_ID") ENABLE;
